/// Service that provides 365 unique daily motivational messages from the Bhagavad Gita.
/// Messages rotate based on the day of the year (1-365).
class DailyMessageService {
  /// Get the motivational message for a specific day of the year.
  /// [dayOfYear] should be between 1 and 365 (366 for leap years, which wraps to day 365).
  static String getMessageForDay(int dayOfYear) {
    // Handle leap years by wrapping day 366 to day 365
    final index = (dayOfYear - 1).clamp(0, 364);
    return _messages[index];
  }

  /// Get today's motivational message based on current date.
  static String getTodaysMessage() {
    final now = DateTime.now();
    final dayOfYear = now.difference(DateTime(now.year, 1, 1)).inDays + 1;
    return getMessageForDay(dayOfYear);
  }

  /// 365 unique motivational messages from the Bhagavad Gita.
  /// Organized by themes: Karma Yoga, Bhakti, Jnana, Dharma, Discipline, etc.
  static final List<String> _messages = [
    // Days 1-30: New Beginnings & Karma Yoga
    "Your spiritual journey begins today! Krishna says: 'Perform your duty with dedication.' 🙏",
    "Day 2 of wisdom! 'You have the right to work, but not to the fruits.' Keep going! 🌟",
    "The path of action calls you! 'Yoga is skill in action.' Maintain your streak! 💪",
    "Krishna awaits! 'One who sees inaction in action, and action in inaction, is wise.' 📿",
    "Your dedication shines! 'The soul is neither born nor does it die.' Continue your journey! ✨",
    "Another day of growth! 'When meditation is mastered, the mind is unwavering like a flame.' 🕉️",
    "Maya cannot break your focus! 'The mind is restless, but it can be controlled through practice.' 🧘",
    "Consistency is key! 'Little by little, through patience and repeated effort, the mind will become stilled.' 🌸",
    "Your streak reflects discipline! 'One who is not disturbed by happiness and distress is fit for liberation.' 🙏",
    "Keep the flame alive! 'As a lamp in a windless place does not waver, so the yogi remains steady.' 🪔",

    "Karma Yoga guides you! 'Perform your duty equipoised, abandoning attachment to success or failure.' ⚖️",
    "The Gita calls! 'One who has control over the mind is tranquil in heat and cold, pleasure and pain.' 🌈",
    "Your soul evolves daily! 'The embodied soul casts off worn-out bodies and enters new ones.' 🦋",
    "Wisdom grows within! 'When your intelligence transcends delusion, you shall become indifferent to what has been heard.' 📖",
    "Another step forward! 'Strive constantly to serve the welfare of the world.' 🌍",
    "Your practice matters! 'Yoga is the journey of the self, through the self, to the self.' 🛤️",
    "Detachment brings peace! 'One who neither rejoices nor hates is dear to Me.' 💙",
    "The path is clear! 'Abandon all varieties of dharmas and just surrender unto Me.' 🙇",
    "Your effort is sacred! 'Whatever you do, do it as an offering to Me.' 🌺",
    "Steadiness wins! 'The yogi whose mind is fixed on Me verily attains the highest perfection.' ⛰️",

    "Knowledge illuminates! 'The light of one candle is not diminished by lighting another.' 🕯️",
    "Your streak is your tapas! 'Through austerity, purity, and self-control, one attains the supreme.' 🔥",
    "Action without attachment! 'Perform your prescribed duty, for action is better than inaction.' 🎯",
    "The self is eternal! 'For the soul there is neither birth nor death.' ♾️",
    "Discipline creates freedom! 'One who is self-controlled and unattached finds happiness within.' 😌",
    "Your journey continues! 'Even a little practice of this dharma protects one from great fear.' 🛡️",
    "Equanimity is strength! 'Treat pleasure and pain, gain and loss, victory and defeat alike.' ⚔️",
    "The wise persist! 'One who has faith and is sincere in practice attains knowledge.' 📚",
    "Your dedication inspires! 'The self-controlled soul who moves among sense objects is at peace.' 🕊️",
    "Another day, another victory! 'One who sees Me in all beings and all beings in Me never loses sight of Me.' 👁️",

    // Days 31-60: Bhakti & Devotion
    "Devotion purifies! 'Whatever you do, offer it to Me with love.' 💝",
    "Krishna is with you! 'I am the beginning, the middle, and the end of all beings.' 🌅",
    "Love transcends all! 'One who worships Me with devotion is in Me, and I am in them.' 🤲",
    "Your heart knows the way! 'Fix your mind on Me alone and you shall dwell in Me.' 💭",
    "Surrender brings peace! 'Abandon all dharmas and surrender to Me alone.' 🙏",
    "Faith moves mountains! 'To those who worship Me with devotion, I give the understanding.' 🏔️",
    "The Lord protects! 'I deliver them from the ocean of birth and death.' 🌊",
    "Your love is returned! 'As you approach Me, so I receive you.' 🤗",
    "Devotion is the path! 'One who offers Me a leaf, a flower, fruit, or water with love, I accept it.' 🍃",
    "The supreme refuge! 'Think of Me, become My devotee, worship Me, and bow down to Me.' 🙇‍♂️",

    "Pure intention matters! 'I look to the heart, not the offering.' ❤️",
    "Your practice is worship! 'In whatever way people surrender unto Me, I reward them accordingly.' 🎁",
    "The divine is near! 'I am seated in everyone's heart.' 💓",
    "Love conquers all! 'One who sees Me everywhere and sees everything in Me never loses Me.' 🔗",
    "Devotion is simple! 'With a pure heart, offer everything to Me.' 🧡",
    "The path of love! 'One who is devoted to Me, thinking of Me always, I am easy to obtain.' 🛤️",
    "Your faith sustains you! 'Those who worship Me with faith, I consider them perfect in yoga.' ✨",
    "The Lord listens! 'Whatever you offer with devotion, I accept.' 👂",
    "Bhakti is supreme! 'Among all yogas, one who worships Me with faith is most dear to Me.' 👑",
    "Your heart is the temple! 'I dwell in the hearts of all beings.' 🏛️",

    "Divine grace flows! 'To those constantly devoted, I give the understanding by which they come to Me.' 🌊",
    "Love is the answer! 'One who loves Me is never lost, and I am never lost to them.' 🧭",
    "Surrender your worries! 'Cast all your burdens upon Me.' 🎒",
    "The supreme friend! 'I am the friend of all beings.' 🤝",
    "Your devotion protects! 'My devotee is never lost.' 🛡️",
    "Faith is your strength! 'One who has faith in Me and is devoted to Me attains Me.' 💪",
    "The divine embrace! 'Come to Me for refuge and I shall free you from all sins.' 🤗",
    "Love without fear! 'One who loves Me fears nothing.' 🦁",
    "Your heart's desire! 'I fulfill the desires of those who worship Me with love.' 🌟",
    "The eternal bond! 'Between the devotee and Me, there is no separation.' 🔗",

    // Days 61-90: Jnana Yoga & Wisdom
    "Knowledge liberates! 'When you are enlightened, you shall see all beings in your Self.' 💡",
    "Wisdom dawns! 'The fire of knowledge burns all karma to ashes.' 🔥",
    "The self is supreme! 'Know the Self to be distinct from the body.' 🧘‍♀️",
    "Ignorance fades! 'Knowledge removes the darkness of ignorance like a lamp.' 🪔",
    "Truth reveals itself! 'The wise see with equal vision a learned scholar and an outcast.' 👁️",
    "Understanding deepens! 'One who knows the truth about My divine birth and activities is not born again.' 🌀",
    "The eternal witness! 'The Self is the witness, ever-present and unchanging.' 👀",
    "Knowledge is power! 'There is nothing more purifying than knowledge.' 💎",
    "Wisdom guides! 'One established in knowledge sees the Self in all beings.' 🌍",
    "The truth within! 'Realize the Self and be free from birth and death.' ♾️",

    "Discernment is key! 'Distinguish between the real and the unreal.' 🔍",
    "The knower is free! 'One who knows Me as the Supreme Lord is freed from all sins.' 🕊️",
    "Wisdom transcends! 'The wise grieve neither for the living nor the dead.' 🌅",
    "Knowledge is eternal! 'The Self is never born and never dies.' ⏳",
    "Understanding brings peace! 'One who knows the truth is not bewildered.' 😌",
    "The path of wisdom! 'Through knowledge, one attains the supreme peace.' 🛤️",
    "Truth is simple! 'The Self is one, though sages call it by many names.' 🕉️",
    "Wisdom destroys doubt! 'Cut through your doubts with the sword of knowledge.' ⚔️",
    "The eternal reality! 'That which is real never ceases to be.' 🌟",
    "Knowledge is light! 'Ignorance is darkness; knowledge is illumination.' 💫",

    "The wise are steady! 'One established in wisdom is not shaken by adversity.' 🏔️",
    "Understanding is freedom! 'Know the Self and be liberated.' 🦅",
    "Truth is one! 'The wise see unity in diversity.' 🌈",
    "Knowledge purifies! 'Nothing in this world is as purifying as knowledge.' 🌊",
    "The self-realized! 'One who knows the Self has nothing to fear.' 🛡️",
    "Wisdom is eternal! 'This knowledge was taught in ancient times and remains true today.' 📜",
    "The knower is blissful! 'One established in Self-knowledge experiences supreme bliss.' 😊",
    "Understanding transcends! 'The wise are not bound by the fruits of action.' 🎯",
    "Truth liberates! 'Knowledge of the Self destroys all bondage.' 🔓",
    "The eternal truth! 'The Self is beyond birth, death, and change.' ∞",

    // Days 91-120: Dharma & Duty
    "Dharma calls! 'Better is one's own dharma, though imperfect, than another's well performed.' 📯",
    "Duty is sacred! 'Perform your prescribed duty, for action is superior to inaction.' ⚖️",
    "Righteousness prevails! 'Whenever dharma declines, I manifest Myself.' 🌅",
    "Your role matters! 'By performing one's own duty, one attains perfection.' 🎭",
    "Stand for truth! 'It is better to die in one's own dharma than to follow another's.' ⚔️",
    "Duty without attachment! 'Perform your duty without desire for results.' 🎯",
    "Dharma protects! 'One who follows dharma is protected by dharma.' 🛡️",
    "The righteous path! 'Establish yourself in dharma and perform your duty.' 🛤️",
    "Your purpose is clear! 'Every being has a unique dharma to fulfill.' 🌟",
    "Duty is worship! 'Performing one's duty is the highest form of worship.' 🙏",

    "Righteousness wins! 'Truth alone triumphs, not falsehood.' 👑",
    "Your dharma is your strength! 'One established in dharma fears nothing.' 💪",
    "The path of duty! 'Follow your dharma with dedication and sincerity.' 🚶",
    "Dharma sustains! 'The universe is upheld by dharma.' 🌍",
    "Your role is divine! 'Every action performed in dharma is sacred.' ✨",
    "Duty brings peace! 'One who performs duty without attachment finds peace.' 😌",
    "The righteous warrior! 'Fight for dharma without fear or hesitation.' ⚔️",
    "Your purpose unfolds! 'Trust in dharma and your path will be clear.' 🧭",
    "Dharma is eternal! 'The principles of dharma are timeless.' ⏳",
    "Duty is freedom! 'One who performs duty selflessly is truly free.' 🕊️",

    "The call of dharma! 'Answer the call of duty with courage.' 📯",
    "Your actions matter! 'Every action in line with dharma creates positive karma.' 🌱",
    "Righteousness is strength! 'One rooted in dharma cannot be shaken.' 🌳",
    "Duty is your yoga! 'Performing one's duty is the highest yoga.' 🧘",
    "The dharmic path! 'Walk the path of righteousness without wavering.' 🛤️",
    "Your role is sacred! 'Honor your dharma as you would honor the divine.' 🙇",
    "Dharma guides! 'In times of doubt, dharma shows the way.' 💡",
    "Duty without ego! 'Perform your duty humbly, without pride.' 🌾",
    "The righteous life! 'A life lived in dharma is a life well-lived.' 🌅",
    "Your dharma is your gift! 'Fulfill your dharma as your offering to the world.' 🎁",

    // Days 121-150: Discipline & Self-Control
    "Discipline is power! 'One who has control over the senses is truly powerful.' 💪",
    "The mind is key! 'For one who has conquered the mind, it is the best friend.' 🧠",
    "Self-control wins! 'One who is self-controlled attains the supreme.' 🏆",
    "Mastery within! 'Conquer yourself and you conquer the world.' 🌍",
    "The disciplined path! 'Through discipline and practice, one attains perfection.' 🛤️",
    "Your will is strong! 'The mind can be your friend or your enemy; choose wisely.' ⚖️",
    "Control brings peace! 'One who has mastered the senses experiences inner peace.' 😌",
    "Discipline is freedom! 'True freedom comes from self-mastery.' 🕊️",
    "The steady mind! 'A disciplined mind is like a calm lake.' 🏞️",
    "Your practice strengthens! 'Through constant practice, the mind becomes steady.' 🧘",

    "Restraint is wisdom! 'One who restrains the senses is truly wise.' 🦉",
    "The controlled self! 'Master your senses and you master your destiny.' 🎯",
    "Discipline daily! 'Small acts of discipline lead to great transformation.' 🌱",
    "Your focus sharpens! 'A disciplined mind cuts through distractions.' ⚔️",
    "Self-mastery is yoga! 'Yoga is the control of the modifications of the mind.' 🕉️",
    "The disciplined warrior! 'One who conquers the self is the greatest warrior.' 🛡️",
    "Your strength grows! 'Every day of discipline makes you stronger.' 💎",
    "Control your desires! 'One who is not swayed by desires finds lasting peace.' 🌊",
    "The steady soul! 'A disciplined soul is not disturbed by the dualities of life.' ⚖️",
    "Your will prevails! 'Through discipline, you shape your destiny.' 🔨",

    "Mastery is gradual! 'Little by little, through practice, the mind is tamed.' 🐘",
    "The controlled breath! 'Control the breath and you control the mind.' 🌬️",
    "Discipline is devotion! 'Your daily practice is your offering to the divine.' 🙏",
    "Your focus is sharp! 'A disciplined mind is like a sharpened sword.' ⚔️",
    "Self-control liberates! 'Freedom comes from mastering yourself, not others.' 🔓",
    "The disciplined life! 'A life of discipline is a life of purpose.' 🎯",
    "Your practice is sacred! 'Every moment of discipline is a step toward the divine.' 👣",
    "Control brings clarity! 'A controlled mind sees clearly.' 👁️",
    "The steady path! 'Discipline keeps you on the path when motivation fades.' 🛤️",
    "Your will is divine! 'Through self-control, you align with the divine will.' ✨",

    // Days 151-180: Equanimity & Balance
    "Balance is key! 'Treat pleasure and pain, gain and loss, victory and defeat alike.' ⚖️",
    "Equanimity brings peace! 'One who is balanced in all situations finds lasting peace.' 😌",
    "The steady mind! 'Be steady in success and failure.' 🧘",
    "Your balance is strength! 'One who is not swayed by dualities is truly strong.' 💪",
    "The middle path! 'Yoga is not for one who eats too much or too little.' 🛤️",
    "Equanimity is wisdom! 'The wise remain balanced in all circumstances.' 🦉",
    "Your center holds! 'Find your center and remain there.' 🎯",
    "Balance in action! 'Perform your duty with equanimity.' ⚖️",
    "The balanced soul! 'One who is balanced is dear to Me.' 💙",
    "Your peace is within! 'External circumstances cannot disturb one who is balanced.' 🏞️",

    "Equanimity is yoga! 'Yoga is evenness of mind.' 🕉️",
    "The balanced life! 'Live with balance and you live with grace.' 🌸",
    "Your stability grows! 'Every day of practice increases your inner stability.' 🌳",
    "Balance brings clarity! 'A balanced mind sees truth clearly.' 👁️",
    "The even path! 'Walk the middle path with steadiness.' 🚶",
    "Your equanimity shines! 'One who is balanced radiates peace.' ✨",
    "Balance in all! 'Be balanced in work and rest, eating and fasting.' ⚖️",
    "The steady heart! 'A balanced heart is not disturbed by the waves of emotion.' 🌊",
    "Your center is strong! 'Rooted in equanimity, you cannot be shaken.' 🏔️",
    "Balance is freedom! 'Freedom comes from being balanced in all situations.' 🕊️",

    "Equanimity in action! 'Perform all actions with an even mind.' 🎯",
    "The balanced warrior! 'Fight with equanimity, without hatred or attachment.' ⚔️",
    "Your peace is unshakable! 'One established in equanimity cannot be disturbed.' 🛡️",
    "Balance brings joy! 'True joy comes from inner balance, not external circumstances.' 😊",
    "The even mind! 'Cultivate evenness of mind in all situations.' 🧠",
    "Your balance is your power! 'A balanced person is powerful beyond measure.' 💎",
    "Equanimity is strength! 'The strength of equanimity surpasses all other strengths.' 🦁",
    "The balanced path! 'Walk the path of balance and you walk with the divine.' 👣",
    "Your steadiness inspires! 'A balanced soul inspires others.' 🌟",
    "Balance is the way! 'The way of yoga is the way of balance.' 🛤️",

    // Days 181-210: Detachment & Renunciation
    "Detachment frees! 'One who is detached from the fruits of action is truly free.' 🕊️",
    "Let go and grow! 'Renounce attachment and you shall find peace.' 🌱",
    "The detached mind! 'Work without attachment to results.' 🎯",
    "Your freedom awaits! 'Detachment is the key to liberation.' 🔓",
    "Renunciation is wisdom! 'The wise renounce the fruits of action.' 🦉",
    "The unattached soul! 'One who is unattached is not bound by karma.' ♾️",
    "Your peace is within! 'Detachment brings inner peace.' 😌",
    "Let go of outcomes! 'Focus on action, not results.' 🎯",
    "The free spirit! 'One who is detached moves through life with grace.' 🦋",
    "Your liberation is near! 'Through detachment, you approach liberation.' 🌅",

    "Renounce and rejoice! 'Renunciation of attachment brings lasting joy.' 😊",
    "The detached warrior! 'Fight without attachment to victory or defeat.' ⚔️",
    "Your freedom grows! 'Every act of detachment increases your freedom.' 🌳",
    "Let go of fear! 'Detachment removes fear.' 🛡️",
    "The unbound soul! 'One who is detached is not bound by anything.' 🔗",
    "Your peace deepens! 'Detachment deepens your inner peace.' 🏞️",
    "Renunciation is strength! 'The strength to let go is the greatest strength.' 💪",
    "The free mind! 'A mind free from attachment is a mind at peace.' 🧠",
    "Your liberation unfolds! 'Step by step, detachment leads to liberation.' 👣",
    "Let go and trust! 'Detach from outcomes and trust the divine.' 🙏",

    "The detached path! 'Walk the path of detachment with courage.' 🛤️",
    "Your freedom is divine! 'Detachment aligns you with the divine will.' ✨",
    "Renounce and rise! 'Renunciation elevates the soul.' 🦅",
    "The unattached heart! 'A heart free from attachment is a heart full of love.' ❤️",
    "Your peace is eternal! 'Detachment brings eternal peace.' ♾️",
    "Let go of control! 'Surrender control and find true freedom.' 🌊",
    "The free soul! 'One who is detached is truly free.' 🕊️",
    "Your liberation is certain! 'Through detachment, liberation is assured.' 🌟",
    "Renunciation is love! 'True love is detached from possession.' 💙",
    "The unbound life! 'Live detached and live fully.' 🌈",

    // Days 211-240: Inner Peace & Tranquility
    "Peace is within! 'The peace you seek is already within you.' 🏞️",
    "Tranquility dawns! 'A tranquil mind reflects the divine.' 🌅",
    "Your calm is strength! 'Inner peace is the greatest strength.' 💎",
    "The peaceful soul! 'One who is peaceful is dear to Me.' 💙",
    "Stillness speaks! 'In stillness, the divine voice is heard.' 🤫",
    "Your peace radiates! 'A peaceful soul radiates light.' ✨",
    "The calm mind! 'A calm mind is a clear mind.' 🧠",
    "Tranquility is yoga! 'Yoga brings tranquility to the restless mind.' 🕉️",
    "Your inner sanctuary! 'Find peace in your inner sanctuary.' 🏛️",
    "The still waters! 'Be like still water, reflecting the truth.' 💧",

    "Peace is power! 'The power of peace surpasses all other powers.' 🦁",
    "The tranquil heart! 'A tranquil heart is not disturbed by the world.' ❤️",
    "Your serenity grows! 'Every moment of practice deepens your serenity.' 🌱",
    "The peaceful warrior! 'Fight with peace in your heart.' ⚔️",
    "Stillness is wisdom! 'In stillness, wisdom arises.' 🦉",
    "Your calm is divine! 'Inner calm is a reflection of the divine.' 🙏",
    "The serene mind! 'A serene mind is a happy mind.' 😊",
    "Tranquility liberates! 'Peace of mind leads to liberation.' 🕊️",
    "Your peace is unshakable! 'Rooted in peace, you cannot be disturbed.' 🏔️",
    "The still soul! 'A still soul experiences the divine.' ✨",

    "Peace in action! 'Perform all actions with inner peace.' 🎯",
    "The tranquil path! 'Walk the path of tranquility.' 🛤️",
    "Your serenity inspires! 'A serene soul inspires others.' 🌟",
    "The peaceful life! 'A life of peace is a life of grace.' 🌸",
    "Stillness is strength! 'In stillness, you find your true strength.' 💪",
    "Your calm prevails! 'Inner calm prevails over outer chaos.' 🌊",
    "The serene warrior! 'Be serene in the midst of battle.' ⚔️",
    "Tranquility is bliss! 'True bliss comes from inner tranquility.' 😌",
    "Your peace is eternal! 'The peace within is eternal.' ♾️",
    "The still mind! 'A still mind reflects the infinite.' 🌌",

    // Days 241-270: Compassion & Love
    "Love all beings! 'See the divine in all beings.' 👁️",
    "Compassion heals! 'A compassionate heart heals itself and others.' ❤️",
    "Your love is divine! 'Love without condition is divine love.' 💙",
    "The compassionate soul! 'One who is compassionate is dear to Me.' 🙏",
    "Love transcends! 'Love transcends all boundaries.' 🌈",
    "Your kindness matters! 'Every act of kindness is an act of worship.' 🌸",
    "The loving heart! 'A loving heart is a pure heart.' 💖",
    "Compassion is strength! 'True strength lies in compassion.' 💪",
    "Your love radiates! 'A loving soul radiates divine light.' ✨",
    "The kind warrior! 'Fight with compassion in your heart.' ⚔️",

    "Love is the way! 'The way of love is the way to the divine.' 🛤️",
    "The compassionate mind! 'A compassionate mind sees unity in all.' 🧠",
    "Your love grows! 'Every day of practice deepens your capacity to love.' 🌱",
    "The loving soul! 'One who loves all beings is truly free.' 🕊️",
    "Compassion liberates! 'Compassion frees the heart from bondage.' 🔓",
    "Your kindness shines! 'Let your kindness shine like the sun.' ☀️",
    "The loving path! 'Walk the path of love with courage.' 👣",
    "Compassion is wisdom! 'True wisdom is rooted in compassion.' 🦉",
    "Your love is eternal! 'The love within is eternal.' ♾️",
    "The kind heart! 'A kind heart is a happy heart.' 😊",

    "Love without fear! 'Love fearlessly and completely.' 🦁",
    "The compassionate warrior! 'Be compassionate even in conflict.' ⚔️",
    "Your love heals! 'Love has the power to heal all wounds.' 🩹",
    "The loving life! 'A life of love is a life well-lived.' 🌅",
    "Compassion is power! 'The power of compassion is infinite.' 💎",
    "Your kindness inspires! 'A kind soul inspires others to be kind.' 🌟",
    "The loving mind! 'A mind filled with love is a mind at peace.' 🧠",
    "Compassion is yoga! 'Yoga is union through love and compassion.' 🕉️",
    "Your love is your strength! 'Love is the greatest strength.' 💪",
    "The kind soul! 'A kind soul reflects the divine.' ✨",

    // Days 271-300: Faith & Surrender
    "Faith moves mountains! 'With faith, all things are possible.' 🏔️",
    "Surrender and soar! 'Surrender to the divine and you shall soar.' 🦅",
    "Your faith is strong! 'Faith is the foundation of spiritual life.' 🏛️",
    "The surrendered soul! 'One who surrenders to Me is never lost.' 🙏",
    "Trust the divine! 'Trust in the divine plan.' 🧭",
    "Your faith sustains! 'Faith sustains you in times of doubt.' 🌳",
    "The path of surrender! 'Surrender is the highest yoga.' 🕉️",
    "Faith brings peace! 'Faith brings peace to the troubled mind.' 😌",
    "Your surrender is strength! 'True strength lies in surrender.' 💪",
    "The faithful heart! 'A faithful heart is never alone.' ❤️",

    "Trust and triumph! 'Trust in the divine and you shall triumph.' 🏆",
    "The surrendered mind! 'A mind surrendered to the divine is at peace.' 🧠",
    "Your faith grows! 'Every day of practice strengthens your faith.' 🌱",
    "The trusting soul! 'One who trusts the divine is truly free.' 🕊️",
    "Surrender liberates! 'Surrender is the key to liberation.' 🔓",
    "Your faith shines! 'Let your faith shine like a beacon.' 🔦",
    "The path of trust! 'Walk the path of trust with courage.' 🛤️",
    "Faith is wisdom! 'True wisdom is rooted in faith.' 🦉",
    "Your surrender is complete! 'Complete surrender brings complete peace.' ♾️",
    "The faithful warrior! 'Fight with faith in your heart.' ⚔️",

    "Trust the process! 'Trust the divine process.' 🌀",
    "The surrendered life! 'A life of surrender is a life of grace.' 🌸",
    "Your faith is divine! 'Faith connects you to the divine.' ✨",
    "The trusting heart! 'A trusting heart is a happy heart.' 😊",
    "Surrender and receive! 'Surrender and receive divine grace.' 🎁",
    "Your faith prevails! 'Faith prevails over all obstacles.' 🛡️",
    "The path of faith! 'The path of faith leads to the divine.' 🌅",
    "Trust in action! 'Act with faith and trust the outcome.' 🎯",
    "Your surrender is sacred! 'Surrender is the most sacred act.' 🙏",
    "The faithful soul! 'A faithful soul is dear to the divine.' 💙",

    // Days 301-330: Perseverance & Strength
    "Persist and prevail! 'Perseverance leads to perfection.' 🏆",
    "Your strength is divine! 'Divine strength flows through you.' 💪",
    "The persistent soul! 'One who persists attains the goal.' 🎯",
    "Never give up! 'The path may be long, but the goal is certain.' 🛤️",
    "Your courage inspires! 'Courage in the face of adversity is divine.' 🦁",
    "The strong warrior! 'Be strong and fight on.' ⚔️",
    "Perseverance wins! 'Perseverance conquers all obstacles.' 🏔️",
    "Your determination grows! 'Every day of practice strengthens your determination.' 🌱",
    "The resilient soul! 'Resilience is the mark of a true yogi.' 🧘",
    "Strength through struggle! 'Struggle makes you stronger.' 💎",

    "Persist in practice! 'Consistent practice leads to mastery.' 🎯",
    "Your strength is tested! 'Tests reveal your true strength.' 🛡️",
    "The enduring soul! 'Endurance is the path to enlightenment.' 🌅",
    "Never surrender! 'Never surrender to weakness.' 🦅",
    "Your perseverance shines! 'Let your perseverance shine.' ✨",
    "The strong mind! 'A strong mind overcomes all obstacles.' 🧠",
    "Courage in action! 'Act with courage, without fear.' 🎯",
    "Your determination is divine! 'Divine determination flows through you.' 🙏",
    "The persistent warrior! 'Persist in your duty without wavering.' ⚔️",
    "Strength in stillness! 'True strength is found in stillness.' 🏞️",

    "Persevere and prosper! 'Perseverance leads to prosperity.' 🌟",
    "Your courage is unshakable! 'Unshakable courage is divine.' 🏔️",
    "The resilient warrior! 'Resilience is the warrior's greatest weapon.' 🛡️",
    "Never falter! 'Faltering is not in your nature.' 🦁",
    "Your strength endures! 'True strength endures all trials.' 💪",
    "The determined soul! 'Determination is the key to success.' 🔑",
    "Persist in dharma! 'Persist in your dharma, no matter what.' 📯",
    "Your courage prevails! 'Courage prevails over all fears.' 🌈",
    "The enduring warrior! 'Endure and you shall triumph.' 🏆",
    "Strength is your birthright! 'Divine strength is your birthright.' 👑",

    // Days 331-365: Unity & Oneness
    "All is one! 'See the one in all and all in one.' 🕉️",
    "Unity in diversity! 'The divine is one, though called by many names.' 🌈",
    "Your oneness shines! 'You are one with all that is.' ✨",
    "The unified soul! 'One who sees unity is truly wise.' 🦉",
    "We are all connected! 'All beings are connected in the divine.' 🔗",
    "Your unity is strength! 'Unity is the greatest strength.' 💪",
    "The one Self! 'The Self is one in all beings.' 👁️",
    "Oneness liberates! 'Realization of oneness brings liberation.' 🕊️",
    "Your connection is divine! 'You are divinely connected to all.' 🙏",
    "The unified mind! 'A mind that sees unity is at peace.' 🧠",

    "All is Brahman! 'Everything is Brahman.' 🌌",
    "Unity in action! 'Act with the awareness of unity.' 🎯",
    "Your oneness is eternal! 'The oneness within is eternal.' ♾️",
    "The connected soul! 'All souls are connected in the divine.' 💙",
    "See the divine in all! 'The divine dwells in all beings.' 👁️",
    "Your unity inspires! 'A soul that sees unity inspires others.' 🌟",
    "The one reality! 'There is only one reality.' 🕉️",
    "Oneness is truth! 'The truth is oneness.' 💎",
    "Your connection is sacred! 'Your connection to all is sacred.' 🙏",
    "The unified life! 'Live with the awareness of unity.' 🌍",

    "All paths lead to one! 'All spiritual paths lead to the one.' 🛤️",
    "Unity is love! 'Love is the expression of unity.' ❤️",
    "Your oneness is bliss! 'Realization of oneness is bliss.' 😊",
    "The one truth! 'Truth is one, paths are many.' 🌅",
    "See yourself in all! 'See yourself in all beings.' 👁️",
    "Your unity is power! 'The power of unity is infinite.' 💪",
    "The connected heart! 'A heart that feels unity is a loving heart.' 💖",
    "Oneness is freedom! 'Freedom comes from realizing oneness.' 🕊️",
    "Your connection endures! 'The connection to all endures forever.' ♾️",
    "The one divine! 'The divine is one, eternal, and infinite.' ✨",

    "All is sacred! 'Everything is sacred in the eyes of the divine.' 🙏",
    "Unity in spirit! 'All spirits are one.' 🌟",
    "Your oneness is complete! 'You are complete in your oneness.' 🕉️",
    "The unified universe! 'The universe is one unified whole.' 🌌",
    "See the divine everywhere! 'The divine is everywhere, in everything.' 👁️",
  ];
}
